### PR TITLE
Receive strategy type

### LINKED ISSUE #20: Packet handling strategy
Currently at the moment a packet is received, it is imediatly processed asynchronously even if you receive them in a single "receive" operation.

We should define a packet handling strategy and apply it to the receive process.

### PR DESCRIPTION
**Pull request by Eastrall**
This PR covers issue #20 and introduces the receive strategy type. The strategy can be configured in the `LiteServerConfiguration` class and has the following states:

- `Default` (packets are processed asynchronously right after being received)
- `Queued` (packets are queued in a `BlockingCollection` once they have been received)

Closes #20

### CODE REVIEW

**Comment by KSExtrez** [comment]
I think that we have some issues,
Well here we handle all messages in a single task, this task wait for finish a handle message and then follow with the next message. (`Queued` behavior)
```csharp
// LiteNetwork.Common.Internal.LiteReceiver
protected virtual void ProcessReceivedMessages(ILiteConnectionToken connectionToken, IEnumerable<byte[]> messages)
{
    // Create a single ask for process all messages
    Task.Run(async () =>
    {
        foreach (var messageBuffer in messages)
        {
            await ProcessReceivedMessage(connectionToken.Connection, messageBuffer); // Wait for finish the process message
        }
    });
}
```
The opposite happens in queued messages, we have a main task that wait for message and then process all messages asynchronously.
```csharp
// LiteNetwork.Server.LiteServerUser
private void ProcessReceivedPackets()
{
    ...
    LiteReceivedMessage message = _receivedMessages.Take(_receiveProcessCancellationToken);

    if (message is not null)
    {
        message.Handle(); // Task.Run(); Create a new task for each message and NO wait for finish
    }
    ...
}
```
Also i think that we can do this less complex, deleting all the Receive logic from `LiteServerUser` and make the changes only in the Receive classes.
```csharp
// LiteNetwork.Server.Internal.LiteServerReceiver
protected override void ProcessReceivedMessages(ILiteConnectionToken connectionToken, IEnumerable<byte[]> messages)
{
    if (_receiveStrategy == ReceiveStrategyType.Default)
    {
        base.ProcessReceivedMessages(connectionToken, messages); // Handle all messages default
       /* 
       foreach (var messageBuffer in messages)
       {
           // Creates a new task for each message and run it asynchronously
           Task.Run(() => ProcessReceivedMessage(connectionToken.Connection, messageBuffer));
       }
       */
    }
    else if (_receiveStrategy == ReceiveStrategyType.Queued)
    {
        // Create a single task to handle all messages
        Task.Run(async () => {
            foreach(var messageBuffer in messages)
            {
                await ProcessReceivedMessage(connectionToken.Connection, messageBuffer); // Wait for finish the process message
            }
        });
    }
}
```

**Comment by Eastrall** [comment]
The way I thought the `Queued` behavior was to process all receive packets in the **exact** same order has they have been received without blocking receive `Task`. 

The `ProcessReceivedMessages()` is called when a `Socket.ReceiveAsync()` operation is completed and all the transfered bytes have been processed. If **at least** one packet is complete during the receive operation, then the `ProcesReceivedMessage()` is called and the packet will be processed asynchronously. This is de `Default` receive strategy type.

On the other hand, the `Queued` strategy **should** put every received packet in a receive queue and be processed separately from the receive process. This is why we have a `Task _receiveTask` and `BlockingCollection` in the `LiteServerUser` to handle this scenario.

Now that you mentionned, the second example lacks an `await` keyword that **should** wait for the message handler task to finish before processing the next one.

To be honnest, I am not completly satistfied of this version because has you mentionned, the receive process is tightly coupled with the `LiteReceiver` and `LiteServerReceiver`. I am going to think about another way to implement that, in a more elegant way.

**Comment by Eastrall** [comment]
Suggestion of implementation:

Instead of having the receive process in the `LiteServerUser`, we could use the `LiteConnectionToken` that is only used in the `LiteReceiver` class. Thus, we could also rename it into `LiteReceiverConnectionToken` but we'll see that later.

When a new user connects to the server, the receiver creates a new token for this client and associates it to the `SocketAsyncEventArgs.UserToken` property. The idea would be to store the receive `Task` and queue into the `LiteConnectionToken` plus a `EnqueueMessage()` method that will add the message to the queue.

Snippet of implementation:

```csharp
public class LiteConnectionToken
{
    private readonly BlockCollection<byte[]> _receiveMessageQueue;
    private readonly Task _receiveTask;
    // cancellation token stuff

    public void EnqueueMessage(byte[] messageBuffer) => _receiveMessageQueue.Add(messageBuffer);

    private async Task ProcessMessageQueue()
    {
        while (!_cancellationToken.IsCancelRequested)
        {
            var message = _receiveMessageQueue.Take(_cancellationToken);

            using ILitePacketStream packetStream = ... // create packet stream using ILitePacketProcessor
            await Connection.HandleMessage(packetStream); // waiting for this packet to be completed to move on the next one
        }
    }
}
```
This could allow us in the futur to reuse this mecanism for the client part.

Any thoughts?

**Comment by KSExtrez** [comment]
I like the changes, now it looks much better :)

**Comment by Eastrall** [comment]
I believe we have something stable and maintanable. 😉 
Let's merge that.

**Pull request merged**
